version: '2'
services:
 db:
   image: postgres
   volumes:
     - ./data/postgresql_data:/var/lib/postgresql/data/
   restart: always

   environment:
    - POSTGRES_HOST_AUTH_METHOD=trust

 web:
   build: .
   command: bash docker-entrypoint.sh
   volumes:
     - .:/code
   ports:
     - "7191:8000"
   depends_on:
     - db
     
    
 # annotator:
 #  build: ./compose/annotator
